int CategoryID(string category)
{
  if ( category == "NoCategory" ) { return( 0 ); }
  if ( category == "Alcohol" ) { return( 1 ); }
  if ( category == "BankCharge" ) { return( 2 ); }
  if ( category == "CarInsurance" ) { return( 3 ); }
  if ( category == "CarPayment" ) { return( 4 ); }
  if ( category == "Charity" ) { return( 5 ); }
  if ( category == "Check" ) { return( 6 ); }
  if ( category == "ChildCare" ) { return( 7 ); }
  if ( category == "Clothing" ) { return( 8 ); }
  if ( category == "Coffee" ) { return( 9 ); }
  if ( category == "CollegeFund" ) { return( 10 ); }
  if ( category == "CreditCard" ) { return( 11 ); }
  if ( category == "Dining" ) { return( 12 ); }
  if ( category == "Doctor" ) { return( 13 ); }
  if ( category == "Drinks" ) { return( 14 ); }
  if ( category == "Education" ) { return( 15 ); }
  if ( category == "Entertainment" ) { return( 16 ); }
  if ( category == "Fines" ) { return( 17 ); }
  if ( category == "Fuel" ) { return( 18 ); }
  if ( category == "Furniture" ) { return( 19 ); }
  if ( category == "GasElectric" ) { return( 20 ); }
  if ( category == "General" ) { return( 21 ); }
  if ( category == "GiftReceived" ) { return( 22 ); }
  if ( category == "GiftsGiven" ) { return( 23 ); }
  if ( category == "Groceries" ) { return( 24 ); }
  if ( category == "Hair" ) { return( 25 ); }
  if ( category == "HomeDownPayment" ) { return( 26 ); }
  if ( category == "Hospital" ) { return( 27 ); }
  if ( category == "HouseDownPayment" ) { return( 28 ); }
  if ( category == "Laundry" ) { return( 29 ); }
  if ( category == "License" ) { return( 30 ); }
  if ( category == "LocalTravel" ) { return( 31 ); }
  if ( category == "Medicine" ) { return( 32 ); }
  if ( category == "Mortgage" ) { return( 33 ); }
  if ( category == "MovingStorage" ) { return( 34 ); }
  if ( category == "OpeningBalance" ) { return( 35 ); }
  if ( category == "Phone" ) { return( 36 ); }
  if ( category == "Recreation" ) { return( 37 ); }
  if ( category == "Registration" ) { return( 38 ); }
  if ( category == "Rent" ) { return( 39 ); }
  if ( category == "RentersInsurance" ) { return( 40 ); }
  if ( category == "RuthIRA" ) { return( 41 ); }
  if ( category == "RuthSalary" ) { return( 42 ); }
  if ( category == "School" ) { return( 43 ); }
  if ( category == "SecurityDeposit" ) { return( 44 ); }
  if ( category == "Service" ) { return( 45 ); }
  if ( category == "Split" ) { return( 46 ); }
  if ( category == "StudentLoan" ) { return( 47 ); }
  if ( category == "TVInternet" ) { return( 48 ); }
  if ( category == "TaxRefund" ) { return( 49 ); }
  if ( category == "Taxes" ) { return( 50 ); }
  if ( category == "ThomasIRA" ) { return( 51 ); }
  if ( category == "ThomasSalary" ) { return( 52 ); }
  if ( category == "Tolls" ) { return( 53 ); }
  if ( category == "Travel" ) { return( 54 ); }
  if ( category == "Vacation" ) { return( 55 ); }
  if ( category == "WorkTravel" ) { return( 56 ); }
  return( -1 );
}
