string CorrectedPayeeCategory(string payee, int *f)
{
  if ( payee == "1020") { *f = 1; return( "Dining" ); }
  if ( payee == "107WestRestaurant") { *f = 1; return( "Dining" ); }
  if ( payee == "18thJudicialCircuit") { *f = 1; return( "Fines" ); }
  if ( payee == "213Cafe") { *f = 1; return( "Dining" ); }
  if ( payee == "529Plan") { *f = 1; return( "CollegeFund" ); }
  if ( payee == "7Eleven") { *f = 1; return( "Dining" ); }
  if ( payee == "A&P") { *f = 1; return( "Groceries" ); }
  if ( payee == "A&W") { *f = 1; return( "Dining" ); }
  if ( payee == "AAA") { *f = 1; return( "Service" ); }
  if ( payee == "AGNTFee") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "AMCCantera") { *f = 1; return( "Entertainment" ); }
  if ( payee == "AT&T") { *f = 1; return( "Entertainment" ); }
  if ( payee == "ATA") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "ATMDeposit") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "ATMWithdrawal") { *f = 1; return( "BankCharge" ); }
  if ( payee == "AandDMiniMart") { *f = 1; return( "Vacation" ); }
  if ( payee == "Acapulcos") { *f = 1; return( "Vacation" ); }
  if ( payee == "AceHardware") { *f = 1; return( "General" ); }
  if ( payee == "Acqua") { *f = 1; return( "Dining" ); }
  if ( payee == "AdagioTeas") { *f = 1; return( "Dining" ); }
  if ( payee == "AdcoHearingProducts") { *f = 1; return( "General" ); }
  if ( payee == "AddysDutchCafes") { *f = 1; return( "Dining" ); }
  if ( payee == "Aeropostale") { *f = 1; return( "Clothing" ); }
  if ( payee == "AgraIndian") { *f = 1; return( "Dining" ); }
  if ( payee == "AguaVerdeCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "AirTran") { *f = 1; return( "Travel" ); }
  if ( payee == "Airtastic") { *f = 1; return( "Entertainment" ); }
  if ( payee == "AjantaIndian") { *f = 1; return( "Dining" ); }
  if ( payee == "AlamoRentACar") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "AlbeeBabyCarriage") { *f = 1; return( "Furniture" ); }
  if ( payee == "Aldi") { *f = 1; return( "Groceries" ); }
  if ( payee == "AlexandriaPastryShop") { *f = 1; return( "Dining" ); }
  if ( payee == "AlfredCossariMD") { *f = 1; return( "Doctor" ); }
  if ( payee == "AlicesMountainMarket") { *f = 1; return( "Groceries" ); }
  if ( payee == "AllState") { *f = 1; return( "CarInsurance" ); }
  if ( payee == "AllianceOne") { *f = 1; return( "Cash" ); }
  if ( payee == "Allium") { *f = 1; return( "Clothing" ); }
  if ( payee == "Altrec") { *f = 1; return( "Clothing" ); }
  if ( payee == "Amazon") { *f = 1; return( "Entertainment" ); }
  if ( payee == "AmazonFashion") { *f = 1; return( "Clothing" ); }
  if ( payee == "AmazonGiftCards") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "AmazonKindle") { *f = 1; return( "Entertainment" ); }
  if ( payee == "AmazonMarketplace") { *f = 1; return( "General" ); }
  if ( payee == "AmazonPrime") { *f = 1; return( "General" ); }
  if ( payee == "AmericaBar&Grill") { *f = 1; return( "Dining" ); }
  if ( payee == "AmericanAirlines") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "AmericanEagleOutfitters") { *f = 1; return( "Clothing" ); }
  if ( payee == "AmericanFidelityMortage") { *f = 1; return( "HouseDownPayment" ); }
  if ( payee == "AmericanPhysicalSociety") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "AmericanTaxi") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "Amerispec") { *f = 1; return( "HomeDownPayment" ); }
  if ( payee == "AmirsFalafel") { *f = 1; return( "Dining" ); }
  if ( payee == "AmocoOil") { *f = 1; return( "Fuel" ); }
  if ( payee == "AmsterdamCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "Amtrack") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "Amtrak") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "AmysHallmark") { *f = 1; return( "Entertainment" ); }
  if ( payee == "AnUncommonCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "AnabananaKids") { *f = 1; return( "Clothing" ); }
  if ( payee == "AndaleMexican") { *f = 1; return( "Dining" ); }
  if ( payee == "AndersonsBookstore") { *f = 1; return( "Entertainment" ); }
  if ( payee == "AndronicosMarketPaloAlto") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "AngiesList") { *f = 1; return( "Furniture" ); }
  if ( payee == "AnnReidSchool") { *f = 1; return( "School" ); }
  if ( payee == "AnnTaylor") { *f = 1; return( "Clothing" ); }
  if ( payee == "AnnTaylor.com") { *f = 1; return( "Clothing" ); }
  if ( payee == "ApolloTaxi") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "AppleBees") { *f = 1; return( "Dining" ); }
  if ( payee == "AppleStore") { *f = 1; return( "Entertainment" ); }
  if ( payee == "Applebees") { *f = 1; return( "Dining" ); }
  if ( payee == "Appletree") { *f = 1; return( "Groceries" ); }
  if ( payee == "Arabugg") { *f = 1; return( "Clothing" ); }
  if ( payee == "Aramark") { *f = 1; return( "Dining" ); }
  if ( payee == "Arbys") { *f = 1; return( "Dining" ); }
  if ( payee == "ArgoTea") { *f = 1; return( "Dining" ); }
  if ( payee == "ArgonneNationalLab") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "ArniesPizza") { *f = 1; return( "Dining" ); }
  if ( payee == "AromasSpecialtyCoffee") { *f = 1; return( "Coffee" ); }
  if ( payee == "ArteCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "ArtopolisCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "AsianChao") { *f = 1; return( "Dining" ); }
  if ( payee == "Asie") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "AspenBarAndGrill") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "AspenBrewingCompany") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "AspenCenterForPhysics") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "AspenMeadowsResort") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "AspenOverEasyCafe") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "AspenSkiing") { *f = 1; return( "Vacation" ); }
  if ( payee == "AtlantaBread") { *f = 1; return( "Dining" ); }
  if ( payee == "AuBonPain") { *f = 1; return( "Dining" ); }
  if ( payee == "AuntieAnnes") { *f = 1; return( "Dining" ); }
  if ( payee == "AutoZone") { *f = 1; return( "Service" ); }
  if ( payee == "Aveda") { *f = 1; return( "Hair" ); }
  if ( payee == "BANKATM") { *f = 1; return( "Cash" ); }
  if ( payee == "BCCC30thStreet") { *f = 1; return( "Dining" ); }
  if ( payee == "BNL") { *f = 1; return( "RuthSalary" ); }
  if ( payee == "BNLChildCare") { *f = 1; return( "ChildCare" ); }
  if ( payee == "BNLWorkTravel") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "BPOil") { *f = 1; return( "Fuel" ); }
  if ( payee == "BPStore") { *f = 1; return( "Dining" ); }
  if ( payee == "BROil") { *f = 1; return( "Vacation" ); }
  if ( payee == "BabiesRUs") { *f = 1; return( "General" ); }
  if ( payee == "BabyAge") { *f = 1; return( "General" ); }
  if ( payee == "BabyCatalog") { *f = 1; return( "Clothing" ); }
  if ( payee == "Baileys") { *f = 1; return( "Dining" ); }
  if ( payee == "BallFactory") { *f = 1; return( "Entertainment" ); }
  if ( payee == "Bar515") { *f = 1; return( "Dining" ); }
  if ( payee == "Barnes&Noble") { *f = 1; return( "Entertainment" ); }
  if ( payee == "BarnesAndNoble") { *f = 1; return( "General" ); }
  if ( payee == "BarnumEq") { *f = 1; return( "Rent" ); }
  if ( payee == "BarnumEq.") { *f = 1; return( "Rent" ); }
  if ( payee == "BarnumHouseLaundry") { *f = 1; return( "Laundry" ); }
  if ( payee == "BassRiverLiquors") { *f = 1; return( "Vacation" ); }
  if ( payee == "BeaconWines") { *f = 1; return( "Dining" ); }
  if ( payee == "BeanAndBagel") { *f = 1; return( "Dining" ); }
  if ( payee == "BedBathAndBeyond") { *f = 1; return( "General" ); }
  if ( payee == "BenAndJerrys") { *f = 1; return( "Dining" ); }
  if ( payee == "BenPao") { *f = 1; return( "Dining" ); }
  if ( payee == "BenjaminMoore") { *f = 1; return( "General" ); }
  if ( payee == "BenjaminMore") { *f = 1; return( "General" ); }
  if ( payee == "BestBuy") { *f = 1; return( "General" ); }
  if ( payee == "BestWestern") { *f = 1; return( "Vacation" ); }
  if ( payee == "BigTimeBrewery") { *f = 1; return( "Dining" ); }
  if ( payee == "BiggbyCoffee") { *f = 1; return( "Coffee" ); }
  if ( payee == "BinnysBeverageDepot") { *f = 1; return( "Groceries" ); }
  if ( payee == "BistroTen") { *f = 1; return( "Dining" ); }
  if ( payee == "BizChairOffice") { *f = 1; return( "General" ); }
  if ( payee == "Blockbuster") { *f = 1; return( "Entertainment" ); }
  if ( payee == "BlueSkysCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "BlueTalonBistro") { *f = 1; return( "Dining" ); }
  if ( payee == "BoardwalkGames") { *f = 1; return( "General" ); }
  if ( payee == "BobJung") { *f = 1; return( "HouseDownPayment" ); }
  if ( payee == "BobbysBurgerPalace") { *f = 1; return( "Dining" ); }
  if ( payee == "Boden") { *f = 1; return( "Clothing" ); }
  if ( payee == "Boingo") { *f = 1; return( "Entertainment" ); }
  if ( payee == "Boingo.com") { *f = 1; return( "Entertainment" ); }
  if ( payee == "BoisJoly") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "BonAppetit") { *f = 1; return( "Dining" ); }
  if ( payee == "BookAreFun") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "Bookmans") { *f = 1; return( "Dining" ); }
  if ( payee == "Borders") { *f = 1; return( "Entertainment" ); }
  if ( payee == "BostonCommon") { *f = 1; return( "Vacation" ); }
  if ( payee == "BostonMBTA") { *f = 1; return( "Dining" ); }
  if ( payee == "BostonMarket") { *f = 1; return( "Dining" ); }
  if ( payee == "BostonUniversity") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "BourbanStreetCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "BreaktimeBilliards") { *f = 1; return( "Dining" ); }
  if ( payee == "BrewCamp") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "BrickLaneCurryHouse") { *f = 1; return( "Dining" ); }
  if ( payee == "BridgeBarEatin") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "BriermereFarms") { *f = 1; return( "Vacation" ); }
  if ( payee == "BriocheDoree") { *f = 1; return( "Dining" ); }
  if ( payee == "BronxZoo") { *f = 1; return( "Entertainment" ); }
  if ( payee == "BrookfieldZoo") { *f = 1; return( "Entertainment" ); }
  if ( payee == "BrookhavenDayCare") { *f = 1; return( "ChildCare" ); }
  if ( payee == "BrookhavenNationalLab") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "BrookhavenNationalLabSalary") { *f = 1; return( "RuthSalary" ); }
  if ( payee == "BrookhavenScienceAssociates") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "BrooksBrothers") { *f = 1; return( "Clothing" ); }
  if ( payee == "BrookstoneRetailStore") { *f = 1; return( "Clothing" ); }
  if ( payee == "BrothersMarket") { *f = 1; return( "Groceries" ); }
  if ( payee == "BudgetRentACar") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "BuffaloWildWings") { *f = 1; return( "Dining" ); }
  if ( payee == "BuildABear") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "BullsEye") { *f = 1; return( "General" ); }
  if ( payee == "BumpsRestaurant") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "BuonItalia") { *f = 1; return( "Dining" ); }
  if ( payee == "BurgerKing") { *f = 1; return( "Dining" ); }
  if ( payee == "BurritoBeach") { *f = 1; return( "Dining" ); }
  if ( payee == "BurritoElito") { *f = 1; return( "Dining" ); }
  if ( payee == "Butera") { *f = 1; return( "Groceries" ); }
  if ( payee == "BuyBuyBaby") { *f = 1; return( "General" ); }
  if ( payee == "CERNHostel") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "CHS@SFO") { *f = 1; return( "Dining" ); }
  if ( payee == "CPZRestaurant") { *f = 1; return( "Dining" ); }
  if ( payee == "CVS") { *f = 1; return( "General" ); }
  if ( payee == "CVSPharmacy") { *f = 1; return( "Medicine" ); }
  if ( payee == "Cablevision") { *f = 1; return( "TVInternet" ); }
  if ( payee == "CafeAllegro") { *f = 1; return( "Dining" ); }
  if ( payee == "CafeAtTheKendall") { *f = 1; return( "Dining" ); }
  if ( payee == "CafeFrida") { *f = 1; return( "Dining" ); }
  if ( payee == "CaffeSwish") { *f = 1; return( "Dining" ); }
  if ( payee == "CaliforniaPizzaKitchen") { *f = 1; return( "Dining" ); }
  if ( payee == "CallFromSwitzerland") { *f = 1; return( "BankCharge" ); }
  if ( payee == "CalvinKlein") { *f = 1; return( "Clothing" ); }
  if ( payee == "CambridgeCommon") { *f = 1; return( "Groceries" ); }
  if ( payee == "CampusCopyCenter") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "CampusDining") { *f = 1; return( "Dining" ); }
  if ( payee == "CampusInnHotel") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "CapeCodCreamery") { *f = 1; return( "Vacation" ); }
  if ( payee == "CappysCarpet") { *f = 1; return( "General" ); }
  if ( payee == "CapriInn") { *f = 1; return( "Vacation" ); }
  if ( payee == "CardValidation") { *f = 1; return( "BankCharge" ); }
  if ( payee == "CareGetActive") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "CaribouCoffee") { *f = 1; return( "Coffee" ); }
  if ( payee == "CarolynSwartz") { *f = 1; return( "Doctor" ); }
  if ( payee == "Carters") { *f = 1; return( "Clothing" ); }
  if ( payee == "CasaDeReyes") { *f = 1; return( "Dining" ); }
  if ( payee == "Caseys") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "CaseysFood") { *f = 1; return( "Dining" ); }
  if ( payee == "Cash") { *f = 1; return( "Cash" ); }
  if ( payee == "Cash-BostonAirport") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "Cash-DobbsFerry") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "Cash-NewYork") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "Cash-Warrenville") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "CashAdvance") { *f = 1; return( "BankCharge" ); }
  if ( payee == "CashRedemption") { *f = 1; return( "GiftReceived" ); }
  if ( payee == "CatamaranResortHotel") { *f = 1; return( "Vacation" ); }
  if ( payee == "CellPhoneShop") { *f = 1; return( "Entertainment" ); }
  if ( payee == "CentralDupageHospital") { *f = 1; return( "Doctor" ); }
  if ( payee == "CentralMarket") { *f = 1; return( "Groceries" ); }
  if ( payee == "CentralParkZoo") { *f = 1; return( "Entertainment" ); }
  if ( payee == "CernHostel") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "CestCheese") { *f = 1; return( "Dining" ); }
  if ( payee == "CharlieChiangsKwai") { *f = 1; return( "Dining" ); }
  if ( payee == "CharliesSteakHouse") { *f = 1; return( "Vacation" ); }
  if ( payee == "Chartwells") { *f = 1; return( "Dining" ); }
  if ( payee == "Chase") { *f = 1; return( "CreditCard" ); }
  if ( payee == "ChaseCreditCardPayment") { *f = 1; return( "CreditCard" ); }
  if ( payee == "CheBellaPizza") { *f = 1; return( "Dining" ); }
  if ( payee == "Check") { *f = 1; return( "Check" ); }
  if ( payee == "ChickFilA") { *f = 1; return( "Dining" ); }
  if ( payee == "Chilis") { *f = 1; return( "Dining" ); }
  if ( payee == "ChinaHouse") { *f = 1; return( "Dining" ); }
  if ( payee == "ChinaMax") { *f = 1; return( "Dining" ); }
  if ( payee == "ChinaTownRestaurant") { *f = 1; return( "Dining" ); }
  if ( payee == "ChineseConsulateGeneral") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "Chipotle") { *f = 1; return( "Dining" ); }
  if ( payee == "ChocolaterieCanonica") { *f = 1; return( "Dining" ); }
  if ( payee == "ChristianBo") { *f = 1; return( "Clothing" ); }
  if ( payee == "CiboExpressGourmet") { *f = 1; return( "Dining" ); }
  if ( payee == "Cinnabon") { *f = 1; return( "Dining" ); }
  if ( payee == "Citgo") { *f = 1; return( "Fuel" ); }
  if ( payee == "CityMeatMarket") { *f = 1; return( "Groceries" ); }
  if ( payee == "CityOfNaperville") { *f = 1; return( "GasElectric" ); }
  if ( payee == "Clarks") { *f = 1; return( "Clothing" ); }
  if ( payee == "ClearyGift") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "ClimateHome") { *f = 1; return( "Clothing" ); }
  if ( payee == "ClinicalPractice") { *f = 1; return( "Doctor" ); }
  if ( payee == "ClintonFoundation") { *f = 1; return( "Charity" ); }
  if ( payee == "Coach") { *f = 1; return( "Clothing" ); }
  if ( payee == "Coastal") { *f = 1; return( "Fuel" ); }
  if ( payee == "CoffeeBeanery") { *f = 1; return( "Coffee" ); }
  if ( payee == "CoffeeCorner") { *f = 1; return( "Coffee" ); }
  if ( payee == "Coldstone") { *f = 1; return( "Dining" ); }
  if ( payee == "ColdstoneCreamery") { *f = 1; return( "Dining" ); }
  if ( payee == "CollegeInnPub") { *f = 1; return( "Dining" ); }
  if ( payee == "CollegetownBagels") { *f = 1; return( "Dining" ); }
  if ( payee == "ColorMeMine") { *f = 1; return( "Entertainment" ); }
  if ( payee == "ColumbiaBookstore") { *f = 1; return( "General" ); }
  if ( payee == "ColumbiaUniversity") { *f = 1; return( "Rent" ); }
  if ( payee == "ColumbiaUniversityAthletics") { *f = 1; return( "Recreation" ); }
  if ( payee == "ColumbiaUniversitySalary") { *f = 1; return( "ThomasSalary" ); }
  if ( payee == "ColumbiaUniversityTransport") { *f = 1; return( "Dining" ); }
  if ( payee == "ColumbusAirport") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "ComfortInn") { *f = 1; return( "Travel" ); }
  if ( payee == "CommodorePerry") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "CommunityFoodAndJuice") { *f = 1; return( "Dining" ); }
  if ( payee == "CompalSRL") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "CompassBooks") { *f = 1; return( "Entertainment" ); }
  if ( payee == "CongreeConvention") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "Connollys") { *f = 1; return( "Dining" ); }
  if ( payee == "ContinentalAirlines") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "ContinentalCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "ConventionsPsychiatry") { *f = 1; return( "Doctor" ); }
  if ( payee == "CookOut") { *f = 1; return( "Dining" ); }
  if ( payee == "CookieDoughCreations") { *f = 1; return( "Dining" ); }
  if ( payee == "CornerBakery") { *f = 1; return( "Dining" ); }
  if ( payee == "Cosi") { *f = 1; return( "Dining" ); }
  if ( payee == "CosleyZoo") { *f = 1; return( "Entertainment" ); }
  if ( payee == "CostPlus") { *f = 1; return( "Clothing" ); }
  if ( payee == "CountryFair") { *f = 1; return( "Vacation" ); }
  if ( payee == "CountryHouse") { *f = 1; return( "Dining" ); }
  if ( payee == "CoupaCafe") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "CourtyardByMarriott") { *f = 1; return( "Vacation" ); }
  if ( payee == "Craftbar") { *f = 1; return( "Dining" ); }
  if ( payee == "CraigsAutoServiceCenter") { *f = 1; return( "Fuel" ); }
  if ( payee == "Crate&Barrel") { *f = 1; return( "Furniture" ); }
  if ( payee == "CrateAndBarrel") { *f = 1; return( "Furniture" ); }
  if ( payee == "Crazy8") { *f = 1; return( "Clothing" ); }
  if ( payee == "Crazy8.com") { *f = 1; return( "Clothing" ); }
  if ( payee == "CreditDueToDebitCardDispute") { *f = 1; return( "CreditCard" ); }
  if ( payee == "CreditReturn") { *f = 1; return( "ChildCare" ); }
  if ( payee == "CreditSuisse") { *f = 1; return( "Cash" ); }
  if ( payee == "Credit_Card") { *f = 1; return( "CreditCard" ); }
  if ( payee == "CrepesOnColumbus") { *f = 1; return( "Dining" ); }
  if ( payee == "CricketMagazine") { *f = 1; return( "Entertainment" ); }
  if ( payee == "CrocsStore") { *f = 1; return( "Clothing" ); }
  if ( payee == "CrossSoundDeli") { *f = 1; return( "Vacation" ); }
  if ( payee == "CrossSoundFerry") { *f = 1; return( "Vacation" ); }
  if ( payee == "CurryClub") { *f = 1; return( "Dining" ); }
  if ( payee == "CurryLeaf") { *f = 1; return( "Dining" ); }
  if ( payee == "D'angelos") { *f = 1; return( "Vacation" ); }
  if ( payee == "DAGOSTINOS") { *f = 1; return( "Dining" ); }
  if ( payee == "DNCTravel") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "DSW") { *f = 1; return( "Clothing" ); }
  if ( payee == "DaGennaroRestaurant") { *f = 1; return( "Dining" ); }
  if ( payee == "DairyQueen") { *f = 1; return( "Dining" ); }
  if ( payee == "Damariscotta") { *f = 1; return( "Vacation" ); }
  if ( payee == "Danastig") { *f = 1; return( "Clothing" ); }
  if ( payee == "DauneReade") { *f = 1; return( "General" ); }
  if ( payee == "DeaBaby") { *f = 1; return( "Clothing" ); }
  if ( payee == "DeanAndDeluca") { *f = 1; return( "Dining" ); }
  if ( payee == "DebitCardProvisionalCredit") { *f = 1; return( "ThomasSalary" ); }
  if ( payee == "DeliceDeFrance") { *f = 1; return( "Dining" ); }
  if ( payee == "Delta") { *f = 1; return( "Travel" ); }
  if ( payee == "DeltaAirlines") { *f = 1; return( "Travel" ); }
  if ( payee == "Deluxe") { *f = 1; return( "Dining" ); }
  if ( payee == "DeluxeCheck") { *f = 1; return( "Cash" ); }
  if ( payee == "DennysRestaurant") { *f = 1; return( "Dining" ); }
  if ( payee == "DestinationMaternity") { *f = 1; return( "Clothing" ); }
  if ( payee == "Diapers.com") { *f = 1; return( "General" ); }
  if ( payee == "DicksSportingGoods") { *f = 1; return( "Clothing" ); }
  if ( payee == "DigitalPhotoFinishing") { *f = 1; return( "School" ); }
  if ( payee == "DiscountTire") { *f = 1; return( "Service" ); }
  if ( payee == "DishCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "Disney.com") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "DisneyStore") { *f = 1; return( "Entertainment" ); }
  if ( payee == "Dollar") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "Dominicks") { *f = 1; return( "Groceries" ); }
  if ( payee == "Doostang") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "DosCaminos") { *f = 1; return( "Dining" ); }
  if ( payee == "DotComMidway") { *f = 1; return( "Dining" ); }
  if ( payee == "DrAtCentralParkWest") { *f = 1; return( "Doctor" ); }
  if ( payee == "DrGidwani") { *f = 1; return( "Doctor" ); }
  if ( payee == "DrugMart") { *f = 1; return( "Medicine" ); }
  if ( payee == "Drugstore") { *f = 1; return( "General" ); }
  if ( payee == "DuPageValleyAnesthesia") { *f = 1; return( "Doctor" ); }
  if ( payee == "DunkinDonuts") { *f = 1; return( "Dining" ); }
  if ( payee == "DupageChildrensMuseum") { *f = 1; return( "Entertainment" ); }
  if ( payee == "DupageMedicalGroup") { *f = 1; return( "Doctor" ); }
  if ( payee == "EZGasoline") { *f = 1; return( "Fuel" ); }
  if ( payee == "EarlyPregnancyTest") { *f = 1; return( "Medicine" ); }
  if ( payee == "EastChinaInn") { *f = 1; return( "Dining" ); }
  if ( payee == "EasyShoppe") { *f = 1; return( "Dining" ); }
  if ( payee == "EatPiada") { *f = 1; return( "Dining" ); }
  if ( payee == "Ebags.com") { *f = 1; return( "Clothing" ); }
  if ( payee == "EddieBauer") { *f = 1; return( "Clothing" ); }
  if ( payee == "EducationAndPsycho") { *f = 1; return( "Doctor" ); }
  if ( payee == "EdwardHealthAndFitness") { *f = 1; return( "Recreation" ); }
  if ( payee == "EdwardHospital") { *f = 1; return( "Dining" ); }
  if ( payee == "EggsInc") { *f = 1; return( "Dining" ); }
  if ( payee == "Eggsperience") { *f = 1; return( "Dining" ); }
  if ( payee == "EinsteinBros") { *f = 1; return( "Dining" ); }
  if ( payee == "EinsteinBrothers") { *f = 1; return( "Dining" ); }
  if ( payee == "ElPortonBar") { *f = 1; return( "Dining" ); }
  if ( payee == "EmiliosTapas") { *f = 1; return( "Dining" ); }
  if ( payee == "EmpanadaJoes") { *f = 1; return( "Dining" ); }
  if ( payee == "EnjoyYourShow") { *f = 1; return( "Entertainment" ); }
  if ( payee == "EnterpriseRentACar") { *f = 1; return( "Vacation" ); }
  if ( payee == "Equifax") { *f = 1; return( "General" ); }
  if ( payee == "EspressoRoyale") { *f = 1; return( "Dining" ); }
  if ( payee == "Esprit") { *f = 1; return( "Clothing" ); }
  if ( payee == "Esso") { *f = 1; return( "Fuel" ); }
  if ( payee == "EurestDining") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "EuropanCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "Expedia") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "ExpressShuttle") { *f = 1; return( "Travel" ); }
  if ( payee == "ExtendedStay") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "ExtremeCoup") { *f = 1; return( "Clothing" ); }
  if ( payee == "ExxonMobil") { *f = 1; return( "Fuel" ); }
  if ( payee == "F&BNassau") { *f = 1; return( "Dining" ); }
  if ( payee == "F&MItaly") { *f = 1; return( "Dining" ); }
  if ( payee == "FAOSchwarz") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "FED_WIRE_CREDIT") { *f = 1; return( "TaxRefund" ); }
  if ( payee == "FEE:_INCOMING_DOMESTIC_WIRE") { *f = 1; return( "GiftReceived" ); }
  if ( payee == "FNALDayCare") { *f = 1; return( "ChildCare" ); }
  if ( payee == "FOREIGN_REMITTANCE_CREDIT") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "FWCLicenseSales") { *f = 1; return( "Entertainment" ); }
  if ( payee == "FacheIndustries") { *f = 1; return( "Fuel" ); }
  if ( payee == "FactoryBrandShoes") { *f = 1; return( "Clothing" ); }
  if ( payee == "FactoryCardOutlet") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "FairOaks") { *f = 1; return( "Dining" ); }
  if ( payee == "FairfieldInn") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "FallenTimbers") { *f = 1; return( "Fuel" ); }
  if ( payee == "FamilyFoods") { *f = 1; return( "Groceries" ); }
  if ( payee == "FamousFamiglia") { *f = 1; return( "Dining" ); }
  if ( payee == "Fandango") { *f = 1; return( "Entertainment" ); }
  if ( payee == "FantasticKids") { *f = 1; return( "Clothing" ); }
  if ( payee == "FastFreshItalian") { *f = 1; return( "Dining" ); }
  if ( payee == "FedEx") { *f = 1; return( "General" ); }
  if ( payee == "FermiResearchHousing") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "FermiWorkTravel") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "Fermilab") { *f = 1; return( "ThomasSalary" ); }
  if ( payee == "FermilabCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "FermilabRecreation") { *f = 1; return( "Recreation" ); }
  if ( payee == "FieldMuseum") { *f = 1; return( "Entertainment" ); }
  if ( payee == "FigsCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "FinbarrsIrishPub") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "FirewoodCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "FirstMidwestBank") { *f = 1; return( "HouseDownPayment" ); }
  if ( payee == "Flavours") { *f = 1; return( "Dining" ); }
  if ( payee == "FlossmoreStation") { *f = 1; return( "Fuel" ); }
  if ( payee == "FlourBakery&Cafe") { *f = 1; return( "Vacation" ); }
  if ( payee == "FlughafenTerminal2Munich") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "FlyingJ") { *f = 1; return( "Dining" ); }
  if ( payee == "FoodCity") { *f = 1; return( "Groceries" ); }
  if ( payee == "FoodMasters") { *f = 1; return( "Dining" ); }
  if ( payee == "FootwearDeckers") { *f = 1; return( "Clothing" ); }
  if ( payee == "ForeignTransactionFee") { *f = 1; return( "BankCharge" ); }
  if ( payee == "ForestAkersGold") { *f = 1; return( "Recreation" ); }
  if ( payee == "ForeverFondue") { *f = 1; return( "Dining" ); }
  if ( payee == "ForeverYogurt") { *f = 1; return( "Dining" ); }
  if ( payee == "Fossil") { *f = 1; return( "Clothing" ); }
  if ( payee == "FourMountainSports") { *f = 1; return( "Vacation" ); }
  if ( payee == "FoxAndHound") { *f = 1; return( "Alcohol" ); }
  if ( payee == "FoxValleyMall") { *f = 1; return( "Groceries" ); }
  if ( payee == "FranklyGourmet") { *f = 1; return( "Dining" ); }
  if ( payee == "FreshensOfCapeCod") { *f = 1; return( "Vacation" ); }
  if ( payee == "FrieldsOfTheZoo") { *f = 1; return( "Dining" ); }
  if ( payee == "Friendlys") { *f = 1; return( "Dining" ); }
  if ( payee == "FrontStreetCantina") { *f = 1; return( "Dining" ); }
  if ( payee == "FronteraGrill") { *f = 1; return( "Dining" ); }
  if ( payee == "Frontier") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "Fun4All") { *f = 1; return( "Entertainment" ); }
  if ( payee == "FunThings") { *f = 1; return( "General" ); }
  if ( payee == "FungWahBus") { *f = 1; return( "Travel" ); }
  if ( payee == "FunivieDelPiccolo") { *f = 1; return( "Entertainment" ); }
  if ( payee == "GIORDANOS") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "GNC") { *f = 1; return( "Medicine" ); }
  if ( payee == "GalaxyStores") { *f = 1; return( "General" ); }
  if ( payee == "Gap") { *f = 1; return( "Clothing" ); }
  if ( payee == "GardenerSupplyCo") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "GarnetHill") { *f = 1; return( "Clothing" ); }
  if ( payee == "GasMart") { *f = 1; return( "Fuel" ); }
  if ( payee == "GatewayArch") { *f = 1; return( "Entertainment" ); }
  if ( payee == "GatewayBakeShop") { *f = 1; return( "Dining" ); }
  if ( payee == "Geico") { *f = 1; return( "CarInsurance" ); }
  if ( payee == "Genesis") { *f = 1; return( "Entertainment" ); }
  if ( payee == "Geordanes") { *f = 1; return( "Dining" ); }
  if ( payee == "GermanGuyInHarlem") { *f = 1; return( "Rent" ); }
  if ( payee == "Getty") { *f = 1; return( "Travel" ); }
  if ( payee == "GettyOil") { *f = 1; return( "Fuel" ); }
  if ( payee == "GiantFood") { *f = 1; return( "Dining" ); }
  if ( payee == "GimmeCoffee") { *f = 1; return( "Coffee" ); }
  if ( payee == "GinnysHallmark") { *f = 1; return( "Dining" ); }
  if ( payee == "Giordanos") { *f = 1; return( "Dining" ); }
  if ( payee == "GlassHalfFull") { *f = 1; return( "Vacation" ); }
  if ( payee == "GloriousBritain") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "GoGoAir") { *f = 1; return( "Entertainment" ); }
  if ( payee == "GoRoma") { *f = 1; return( "Dining" ); }
  if ( payee == "GoebbertsFarm") { *f = 1; return( "Entertainment" ); }
  if ( payee == "GoldenAgeCollectable") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "Goodies") { *f = 1; return( "Vacation" ); }
  if ( payee == "GoodmanTheatre") { *f = 1; return( "Entertainment" ); }
  if ( payee == "GoodyearAutoServiceCenter") { *f = 1; return( "Service" ); }
  if ( payee == "GooseIsland") { *f = 1; return( "Dining" ); }
  if ( payee == "Gotskinds") { *f = 1; return( "Clothing" ); }
  if ( payee == "GourmetBurgerBistro") { *f = 1; return( "Dining" ); }
  if ( payee == "GovernmentCenterParking") { *f = 1; return( "Entertainment" ); }
  if ( payee == "GraceHarold") { *f = 1; return( "Doctor" ); }
  if ( payee == "GraceHsu") { *f = 1; return( "Rent" ); }
  if ( payee == "GraciesCorn") { *f = 1; return( "Clothing" ); }
  if ( payee == "GrainAndWineSpirit") { *f = 1; return( "Groceries" ); }
  if ( payee == "GreatAMSteak") { *f = 1; return( "Dining" ); }
  if ( payee == "GreatAmericanBagel") { *f = 1; return( "Dining" ); }
  if ( payee == "GreatClips") { *f = 1; return( "Hair" ); }
  if ( payee == "GreatHarvest") { *f = 1; return( "Dining" ); }
  if ( payee == "GreenCactusGrill") { *f = 1; return( "Dining" ); }
  if ( payee == "GreenLeafeCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "GreenPeaceUSA") { *f = 1; return( "Charity" ); }
  if ( payee == "Greenberrys") { *f = 1; return( "Dining" ); }
  if ( payee == "Greyhound") { *f = 1; return( "Travel" ); }
  if ( payee == "GringosCantina") { *f = 1; return( "Dining" ); }
  if ( payee == "Groupon") { *f = 1; return( "Entertainment" ); }
  if ( payee == "Guggenheim") { *f = 1; return( "Entertainment" ); }
  if ( payee == "GulfOil") { *f = 1; return( "Fuel" ); }
  if ( payee == "Gymboree") { *f = 1; return( "Clothing" ); }
  if ( payee == "HLAAWalk4Hearing") { *f = 1; return( "Dining" ); }
  if ( payee == "HMS") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "HMSHOST") { *f = 1; return( "Dining" ); }
  if ( payee == "HMSHost") { *f = 1; return( "Dining" ); }
  if ( payee == "HSBC") { *f = 1; return( "HomeDownPayment" ); }
  if ( payee == "HSBC-NOPAYEE") { *f = 1; return( "HSBCTransfer" ); }
  if ( payee == "HSBCDirect") { *f = 1; return( "HouseDownPayment" ); }
  if ( payee == "HSBCInterestPaid") { *f = 1; return( "BankCharge" ); }
  if ( payee == "HSBCOnlineTransfer") { *f = 1; return( "HouseDownPayment" ); }
  if ( payee == "HSBCTransfer") { *f = 1; return( "HouseDownPayment" ); }
  if ( payee == "HaagenDazs") { *f = 1; return( "Dining" ); }
  if ( payee == "HaakonsHall") { *f = 1; return( "Dining" ); }
  if ( payee == "HairCuttery") { *f = 1; return( "Hair" ); }
  if ( payee == "HairCutty") { *f = 1; return( "Hair" ); }
  if ( payee == "HamptonInn") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "HannaAndersson") { *f = 1; return( "Clothing" ); }
  if ( payee == "Hannaford") { *f = 1; return( "Vacation" ); }
  if ( payee == "Hardees") { *f = 1; return( "Dining" ); }
  if ( payee == "HartleyPharmacy") { *f = 1; return( "Medicine" ); }
  if ( payee == "HavanaCentral") { *f = 1; return( "Dining" ); }
  if ( payee == "HeavonOnSeven") { *f = 1; return( "Dining" ); }
  if ( payee == "Heifer") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "Heights") { *f = 1; return( "Dining" ); }
  if ( payee == "HeightsBarAndGrill") { *f = 1; return( "Dining" ); }
  if ( payee == "Hess") { *f = 1; return( "Fuel" ); }
  if ( payee == "HighEnergyBoutique") { *f = 1; return( "Clothing" ); }
  if ( payee == "HiltonHotel") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "HolidayInn") { *f = 1; return( "Vacation" ); }
  if ( payee == "HollywoodPalmsCinema") { *f = 1; return( "Entertainment" ); }
  if ( payee == "HomeDepot") { *f = 1; return( "General" ); }
  if ( payee == "HomeMortagePayment") { *f = 1; return( "Mortgage" ); }
  if ( payee == "Homegoods") { *f = 1; return( "General" ); }
  if ( payee == "Honda") { *f = 1; return( "CarPayment" ); }
  if ( payee == "HoneyDewDonuts") { *f = 1; return( "Vacation" ); }
  if ( payee == "HotelDiStefano") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "HotelMuencher") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "Hotels.com") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "HoundDogs") { *f = 1; return( "Dining" ); }
  if ( payee == "HouseDownPayementInterest") { *f = 1; return( "BankCharge" ); }
  if ( payee == "HoweTravelPlaza") { *f = 1; return( "Vacation" ); }
  if ( payee == "HudsonNews") { *f = 1; return( "Entertainment" ); }
  if ( payee == "HumanRightsCampaign") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "HunanBalcony") { *f = 1; return( "Dining" ); }
  if ( payee == "HuntingtonCountryInn") { *f = 1; return( "Travel" ); }
  if ( payee == "HyannisSportscards") { *f = 1; return( "Vacation" ); }
  if ( payee == "Hyatt") { *f = 1; return( "Travel" ); }
  if ( payee == "HyattRegency") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "IKEA") { *f = 1; return( "Furniture" ); }
  if ( payee == "IMURiverRoom") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "INCOMING_DOMESTIC_WIRE_FEE") { *f = 1; return( "TaxRefund" ); }
  if ( payee == "INCOMING_FOREIGN_WIRE_FEE") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "INTEREST_CHARGE_REVERSAL") { *f = 1; return( "Dining" ); }
  if ( payee == "IPASS") { *f = 1; return( "Tolls" ); }
  if ( payee == "IPass") { *f = 1; return( "Fuel" ); }
  if ( payee == "IQFresh") { *f = 1; return( "Dining" ); }
  if ( payee == "IRAInvestment") { *f = 1; return( "RuthIRA" ); }
  if ( payee == "IRS") { *f = 1; return( "Taxes" ); }
  if ( payee == "IdolGivesBack") { *f = 1; return( "Charity" ); }
  if ( payee == "IlTollway") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "IllinoisBarAndGrill") { *f = 1; return( "Dining" ); }
  if ( payee == "IllinoisDMV") { *f = 1; return( "Registration" ); }
  if ( payee == "IllinoisHealthAndHumanServices") { *f = 1; return( "Doctor" ); }
  if ( payee == "IllinoisSecOfState") { *f = 1; return( "Registration" ); }
  if ( payee == "IllinoisTollway") { *f = 1; return( "Travel" ); }
  if ( payee == "Illy") { *f = 1; return( "Dining" ); }
  if ( payee == "IndecorPaint") { *f = 1; return( "General" ); }
  if ( payee == "IndependentLivingAid") { *f = 1; return( "General" ); }
  if ( payee == "IndianHarvest") { *f = 1; return( "Dining" ); }
  if ( payee == "IndoChineVietnamese") { *f = 1; return( "Dining" ); }
  if ( payee == "IndusValley") { *f = 1; return( "Dining" ); }
  if ( payee == "IndusValleyRestaurant") { *f = 1; return( "Dining" ); }
  if ( payee == "InstituteofReading") { *f = 1; return( "Education" ); }
  if ( payee == "InterMarche") { *f = 1; return( "Groceries" ); }
  if ( payee == "InternationalServiceFee") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "InternationalWines") { *f = 1; return( "Dining" ); }
  if ( payee == "IrvingBlueCanoe") { *f = 1; return( "Vacation" ); }
  if ( payee == "IslipAirport") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "IthacaScienceCenter") { *f = 1; return( "Vacation" ); }
  if ( payee == "IvyLeagueStationary") { *f = 1; return( "General" ); }
  if ( payee == "J&RSound") { *f = 1; return( "General" ); }
  if ( payee == "JAGroup") { *f = 1; return( "Fuel" ); }
  if ( payee == "JCrew") { *f = 1; return( "Clothing" ); }
  if ( payee == "JFKAirport") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "JFKRail") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "Jagdish") { *f = 1; return( "Doctor" ); }
  if ( payee == "JalapenoPaintWerx") { *f = 1; return( "Furniture" ); }
  if ( payee == "JambaJuice") { *f = 1; return( "Dining" ); }
  if ( payee == "JaredGalleriaOfJewelry") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "JasvaleMart") { *f = 1; return( "Fuel" ); }
  if ( payee == "JavaCity") { *f = 1; return( "Dining" ); }
  if ( payee == "JayMart") { *f = 1; return( "Vacation" ); }
  if ( payee == "JeanAtColumbia") { *f = 1; return( "Doctor" ); }
  if ( payee == "JeffEllisManagement") { *f = 1; return( "Recreation" ); }
  if ( payee == "JeffersonScienceAssociates") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "JessaPess") { *f = 1; return( "Clothing" ); }
  if ( payee == "JetRoc") { *f = 1; return( "Travel" ); }
  if ( payee == "JetRock") { *f = 1; return( "Dining" ); }
  if ( payee == "JetRockLaGuardia") { *f = 1; return( "Clothing" ); }
  if ( payee == "JewelOsco") { *f = 1; return( "Groceries" ); }
  if ( payee == "JiffyLube") { *f = 1; return( "Service" ); }
  if ( payee == "JimBestDOPC") { *f = 1; return( "Doctor" ); }
  if ( payee == "JimmyJohns") { *f = 1; return( "Dining" ); }
  if ( payee == "Jimmys") { *f = 1; return( "Dining" ); }
  if ( payee == "JimmysGrill") { *f = 1; return( "Dining" ); }
  if ( payee == "Jockey") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "JoeMamas") { *f = 1; return( "Dining" ); }
  if ( payee == "JohnnyCarinos") { *f = 1; return( "Dining" ); }
  if ( payee == "JoseCuervo") { *f = 1; return( "Vacation" ); }
  if ( payee == "Journeys") { *f = 1; return( "Dining" ); }
  if ( payee == "JuscoyaGoto") { *f = 1; return( "Dining" ); }
  if ( payee == "KFC") { *f = 1; return( "Dining" ); }
  if ( payee == "KaboozsBar&Grill") { *f = 1; return( "Dining" ); }
  if ( payee == "KahunaBusiness") { *f = 1; return( "Groceries" ); }
  if ( payee == "KateSpade") { *f = 1; return( "Clothing" ); }
  if ( payee == "Kebabaluba") { *f = 1; return( "Dining" ); }
  if ( payee == "KernelGourmetPopcorn") { *f = 1; return( "Dining" ); }
  if ( payee == "Kickstarter.com") { *f = 1; return( "Entertainment" ); }
  if ( payee == "KidsTown") { *f = 1; return( "Entertainment" ); }
  if ( payee == "Kidwoot.com") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "KillKullen") { *f = 1; return( "Groceries" ); }
  if ( payee == "KimSMediapolis") { *f = 1; return( "Dining" ); }
  if ( payee == "KingsSupermarket") { *f = 1; return( "Groceries" ); }
  if ( payee == "KingstonAlley") { *f = 1; return( "Dining" ); }
  if ( payee == "Kohls") { *f = 1; return( "Clothing" ); }
  if ( payee == "Kphant") { *f = 1; return( "Clothing" ); }
  if ( payee == "KushiesBabyUsa") { *f = 1; return( "Clothing" ); }
  if ( payee == "LIPA") { *f = 1; return( "GasElectric" ); }
  if ( payee == "LIRR") { *f = 1; return( "Travel" ); }
  if ( payee == "LLBeam") { *f = 1; return( "Clothing" ); }
  if ( payee == "LLNL_REGISTRATION_FEES") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "LMRestaurants") { *f = 1; return( "Dining" ); }
  if ( payee == "LaBonneBoulangerie") { *f = 1; return( "Dining" ); }
  if ( payee == "LaBoulanger") { *f = 1; return( "Dining" ); }
  if ( payee == "LaBrea") { *f = 1; return( "Dining" ); }
  if ( payee == "LaGuardiaAirport") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "LaPalapa") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "LaVazza") { *f = 1; return( "Dining" ); }
  if ( payee == "LachineRapidTours") { *f = 1; return( "Entertainment" ); }
  if ( payee == "LainiesWay") { *f = 1; return( "Entertainment" ); }
  if ( payee == "LakeTahoeFood") { *f = 1; return( "Dining" ); }
  if ( payee == "LakesiteServiceCenter") { *f = 1; return( "Fuel" ); }
  if ( payee == "LalosMexican") { *f = 1; return( "Dining" ); }
  if ( payee == "LamazeClass") { *f = 1; return( "Doctor" ); }
  if ( payee == "LandsEnd") { *f = 1; return( "Clothing" ); }
  if ( payee == "LandsideFC") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "LannaThai") { *f = 1; return( "Dining" ); }
  if ( payee == "LasPalmas") { *f = 1; return( "Dining" ); }
  if ( payee == "LastStopRestaurant") { *f = 1; return( "Dining" ); }
  if ( payee == "LaughFactory") { *f = 1; return( "Entertainment" ); }
  if ( payee == "Lavgrant") { *f = 1; return( "Clothing" ); }
  if ( payee == "LawrenceTKacmarMd") { *f = 1; return( "Doctor" ); }
  if ( payee == "Le") { *f = 1; return( "Dining" ); }
  if ( payee == "LeBusCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "LeChocolatDuBouchard") { *f = 1; return( "Dining" ); }
  if ( payee == "LeMonde") { *f = 1; return( "Dining" ); }
  if ( payee == "LeSaintBock") { *f = 1; return( "Vacation" ); }
  if ( payee == "LeapFrodCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "LemonleafGrill") { *f = 1; return( "Dining" ); }
  if ( payee == "LensCrafters") { *f = 1; return( "Clothing" ); }
  if ( payee == "LifeIsGood") { *f = 1; return( "Clothing" ); }
  if ( payee == "LifeTouchSchoolPortraits") { *f = 1; return( "School" ); }
  if ( payee == "LighthouseInn") { *f = 1; return( "Vacation" ); }
  if ( payee == "LimitedStores") { *f = 1; return( "Clothing" ); }
  if ( payee == "LincolnSquare") { *f = 1; return( "Entertainment" ); }
  if ( payee == "LisaPinto") { *f = 1; return( "Doctor" ); }
  if ( payee == "LittleFairyWings.com") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "LittleThaiRestaurant") { *f = 1; return( "Dining" ); }
  if ( payee == "LivingRoomOfLaJolla") { *f = 1; return( "Dining" ); }
  if ( payee == "Loehmanns") { *f = 1; return( "Clothing" ); }
  if ( payee == "LoneStar") { *f = 1; return( "Dining" ); }
  if ( payee == "LongwoodGardens") { *f = 1; return( "Dining" ); }
  if ( payee == "LorisDesignerShoes") { *f = 1; return( "Clothing" ); }
  if ( payee == "Los") { *f = 1; return( "Clothing" ); }
  if ( payee == "LowEBlueBurSaltLakeCity") { *f = 1; return( "Dining" ); }
  if ( payee == "Lowes") { *f = 1; return( "General" ); }
  if ( payee == "LubePros") { *f = 1; return( "Service" ); }
  if ( payee == "LuigiStefani") { *f = 1; return( "Dining" ); }
  if ( payee == "LuigisHouse") { *f = 1; return( "Dining" ); }
  if ( payee == "LukOil") { *f = 1; return( "Fuel" ); }
  if ( payee == "Lux") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "LylasCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "MDenOnCampus") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "MGHParking") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "MINIMUM_INTEREST_CHARGE") { *f = 1; return( "BankCharge" ); }
  if ( payee == "MTA") { *f = 1; return( "Travel" ); }
  if ( payee == "Macys") { *f = 1; return( "Clothing" ); }
  if ( payee == "MadAnthonysSeattle") { *f = 1; return( "Dining" ); }
  if ( payee == "MaggieIsland") { *f = 1; return( "Dining" ); }
  if ( payee == "MaidBrigade") { *f = 1; return( "MovingStorage" ); }
  if ( payee == "MainStreetBakery") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "MainStreetCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "Maine") { *f = 1; return( "Vacation" ); }
  if ( payee == "MaizeAndBlueDelicates") { *f = 1; return( "Clothing" ); }
  if ( payee == "MalloysFinestWines") { *f = 1; return( "Groceries" ); }
  if ( payee == "MamaLombardis") { *f = 1; return( "Dining" ); }
  if ( payee == "MandLAutoCare") { *f = 1; return( "Fuel" ); }
  if ( payee == "MappsCoffee") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "Marathon") { *f = 1; return( "Fuel" ); }
  if ( payee == "MarathonOil") { *f = 1; return( "Fuel" ); }
  if ( payee == "MarktOnLadiesMile") { *f = 1; return( "Clothing" ); }
  if ( payee == "MarthaVandeWater") { *f = 1; return( "GiftReceived" ); }
  if ( payee == "MartignettiLiquors") { *f = 1; return( "Vacation" ); }
  if ( payee == "Martin's") { *f = 1; return( "Dining" ); }
  if ( payee == "MartiniBar") { *f = 1; return( "Dining" ); }
  if ( payee == "MartinsNewsShops") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "MaryBethMcLaughlin") { *f = 1; return( "Doctor" ); }
  if ( payee == "MassBayCompany") { *f = 1; return( "Vacation" ); }
  if ( payee == "MataFactorCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "MauiBanyan") { *f = 1; return( "Vacation" ); }
  if ( payee == "MauiBanyon") { *f = 1; return( "Vacation" ); }
  if ( payee == "Max&Millie") { *f = 1; return( "Clothing" ); }
  if ( payee == "MaxCaffe") { *f = 1; return( "Dining" ); }
  if ( payee == "MayoraCoffee") { *f = 1; return( "Coffee" ); }
  if ( payee == "MayorgaCoffee") { *f = 1; return( "Coffee" ); }
  if ( payee == "McAlistersDeli") { *f = 1; return( "Dining" ); }
  if ( payee == "McCormickPlace") { *f = 1; return( "Dining" ); }
  if ( payee == "McDonalds") { *f = 1; return( "Dining" ); }
  if ( payee == "MehakCuisineInc") { *f = 1; return( "Dining" ); }
  if ( payee == "Meijer") { *f = 1; return( "Groceries" ); }
  if ( payee == "MeltEmersoy") { *f = 1; return( "Clothing" ); }
  if ( payee == "Menards") { *f = 1; return( "Furniture" ); }
  if ( payee == "MesonSabika") { *f = 1; return( "Dining" ); }
  if ( payee == "MetroNorth") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "MexToGo") { *f = 1; return( "Dining" ); }
  if ( payee == "Michaels") { *f = 1; return( "General" ); }
  if ( payee == "MichaelsMarket") { *f = 1; return( "Groceries" ); }
  if ( payee == "MichiganStateUniversity") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "MidcoastKayak") { *f = 1; return( "Vacation" ); }
  if ( payee == "MiddleKingdomInc") { *f = 1; return( "Clothing" ); }
  if ( payee == "MikesMechanics") { *f = 1; return( "Service" ); }
  if ( payee == "MilanoMarket") { *f = 1; return( "Dining" ); }
  if ( payee == "MillKoreanRestaurant") { *f = 1; return( "Dining" ); }
  if ( payee == "MillersPub") { *f = 1; return( "Dining" ); }
  if ( payee == "MollickEtraEtra") { *f = 1; return( "Doctor" ); }
  if ( payee == "MonkeyJoes") { *f = 1; return( "Dining" ); }
  if ( payee == "MooresGourmetMarket") { *f = 1; return( "Dining" ); }
  if ( payee == "MorningsideBO") { *f = 1; return( "Entertainment" ); }
  if ( payee == "MortonArboretum") { *f = 1; return( "Entertainment" ); }
  if ( payee == "MortonWilliams") { *f = 1; return( "Groceries" ); }
  if ( payee == "Motel6") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "Motherhood") { *f = 1; return( "Clothing" ); }
  if ( payee == "MoutainNectar") { *f = 1; return( "Dining" ); }
  if ( payee == "MowItAll") { *f = 1; return( "MovingStorage" ); }
  if ( payee == "MrsFieldsCookies") { *f = 1; return( "Dining" ); }
  if ( payee == "MughlaiIndian") { *f = 1; return( "Dining" ); }
  if ( payee == "MuseumOfNaturalHistory") { *f = 1; return( "Entertainment" ); }
  if ( payee == "MuseumOfScienceBoston") { *f = 1; return( "Vacation" ); }
  if ( payee == "MysticAquarium") { *f = 1; return( "Vacation" ); }
  if ( payee == "NCOFinancialSystems") { *f = 1; return( "Doctor" ); }
  if ( payee == "NHGenevaAirportHotel") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "NIUOutreach") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "NPR-Chicago") { *f = 1; return( "Charity" ); }
  if ( payee == "NYCParkingGarage") { *f = 1; return( "Clothing" ); }
  if ( payee == "NYCTaxi") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "NapervilleEducationFoundation") { *f = 1; return( "School" ); }
  if ( payee == "NapervilleParkDistrict") { *f = 1; return( "Recreation" ); }
  if ( payee == "NapervillePublicLibrary") { *f = 1; return( "Entertainment" ); }
  if ( payee == "NapervilleSchoolDistrict") { *f = 1; return( "School" ); }
  if ( payee == "NationalExprees") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "NationalGrid") { *f = 1; return( "GasElectric" ); }
  if ( payee == "NationalMilitaryFamilyAssociation") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "NaturalHear") { *f = 1; return( "General" ); }
  if ( payee == "NawabIndian") { *f = 1; return( "Dining" ); }
  if ( payee == "NayyarSons") { *f = 1; return( "Dining" ); }
  if ( payee == "Nespresso") { *f = 1; return( "Coffee" ); }
  if ( payee == "Netflix") { *f = 1; return( "Entertainment" ); }
  if ( payee == "NewHampshireEZPass") { *f = 1; return( "Fines" ); }
  if ( payee == "NewJerseyDevils") { *f = 1; return( "Dining" ); }
  if ( payee == "NewJerseyTransit") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "NewYorkAquarium") { *f = 1; return( "Entertainment" ); }
  if ( payee == "NewYorkState") { *f = 1; return( "TaxRefund" ); }
  if ( payee == "NewYorkStateDMV") { *f = 1; return( "Registration" ); }
  if ( payee == "NewYorkStateTaxes") { *f = 1; return( "Taxes" ); }
  if ( payee == "NicorGas") { *f = 1; return( "GasElectric" ); }
  if ( payee == "Nintendo") { *f = 1; return( "Entertainment" ); }
  if ( payee == "NoodlesAndCo") { *f = 1; return( "Dining" ); }
  if ( payee == "NorthForkBank") { *f = 1; return( "Cash" ); }
  if ( payee == "NorthernPond") { *f = 1; return( "Dining" ); }
  if ( payee == "Novecento") { *f = 1; return( "Dining" ); }
  if ( payee == "Ntrigue") { *f = 1; return( "Hair" ); }
  if ( payee == "NtrigueHairStudio") { *f = 1; return( "Hair" ); }
  if ( payee == "NussbaumAndWu") { *f = 1; return( "Dining" ); }
  if ( payee == "OBriensPub") { *f = 1; return( "Dining" ); }
  if ( payee == "OChaTeaBar") { *f = 1; return( "Dining" ); }
  if ( payee == "ORB") { *f = 1; return( "Travel" ); }
  if ( payee == "OTGManagementJFK") { *f = 1; return( "Dining" ); }
  if ( payee == "OTGManagementTuscon") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "OUTGOING_DOMESTIC_WIRE_FEE") { *f = 1; return( "BankCharges" ); }
  if ( payee == "OakRidgeAssociatedUniversities") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "OakStreetBeachCade") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "OberweisDairy") { *f = 1; return( "Dining" ); }
  if ( payee == "ObriensRestaurant") { *f = 1; return( "Dining" ); }
  if ( payee == "Oceans5Seafood") { *f = 1; return( "Dining" ); }
  if ( payee == "OceansPizzeria") { *f = 1; return( "Dining" ); }
  if ( payee == "OfficeMax") { *f = 1; return( "General" ); }
  if ( payee == "OhareAirport") { *f = 1; return( "Travel" ); }
  if ( payee == "OilXchange") { *f = 1; return( "Service" ); }
  if ( payee == "OldNavy") { *f = 1; return( "Clothing" ); }
  if ( payee == "OlliesNoodleShop") { *f = 1; return( "Dining" ); }
  if ( payee == "OlympicNews") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "OnTheBorder") { *f = 1; return( "Dining" ); }
  if ( payee == "OnTheRocks") { *f = 1; return( "Dining" ); }
  if ( payee == "OneStepAhead") { *f = 1; return( "Clothing" ); }
  if ( payee == "Online_Payment_3785430058_To_Con") { *f = 1; return( "Doctor" ); }
  if ( payee == "OnlySki") { *f = 1; return( "Entertainment" ); }
  if ( payee == "OpenRange") { *f = 1; return( "Alcohol" ); }
  if ( payee == "OpeningBalance") { *f = 1; return( "OpeningBalance" ); }
  if ( payee == "OshKosh") { *f = 1; return( "Clothing" ); }
  if ( payee == "OswaldsPharmacy") { *f = 1; return( "General" ); }
  if ( payee == "Outback") { *f = 1; return( "Dining" ); }
  if ( payee == "P&C") { *f = 1; return( "Groceries" ); }
  if ( payee == "PBAleHouse") { *f = 1; return( "Dining" ); }
  if ( payee == "PJCinemas") { *f = 1; return( "Entertainment" ); }
  if ( payee == "PJClarkes") { *f = 1; return( "Dining" ); }
  if ( payee == "PJVillageGrocery") { *f = 1; return( "Groceries" ); }
  if ( payee == "PacificaSuites") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "PacosTacos") { *f = 1; return( "Dining" ); }
  if ( payee == "PagliaciPizza") { *f = 1; return( "Dining" ); }
  if ( payee == "PalJoeys") { *f = 1; return( "Dining" ); }
  if ( payee == "Palomino") { *f = 1; return( "Recreation" ); }
  if ( payee == "PancherosMexicanGrill") { *f = 1; return( "Dining" ); }
  if ( payee == "PanchoVillas") { *f = 1; return( "Dining" ); }
  if ( payee == "PandaExpress") { *f = 1; return( "Dining" ); }
  if ( payee == "Panera") { *f = 1; return( "Dining" ); }
  if ( payee == "PaneraBread") { *f = 1; return( "Dining" ); }
  if ( payee == "PaninoSportivo") { *f = 1; return( "Dining" ); }
  if ( payee == "PapaJohns") { *f = 1; return( "Dining" ); }
  if ( payee == "Paradies") { *f = 1; return( "Dining" ); }
  if ( payee == "ParadiseBakery&Cafe") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "ParkGateParking") { *f = 1; return( "Tolls" ); }
  if ( payee == "PaulVandeWater") { *f = 1; return( "CollegeFund" ); }
  if ( payee == "PavilionIndian") { *f = 1; return( "Vacation" ); }
  if ( payee == "PayPal") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "PeachesNaturalYogurt") { *f = 1; return( "Dining" ); }
  if ( payee == "PearleVision") { *f = 1; return( "Clothing" ); }
  if ( payee == "PediatricCardiology") { *f = 1; return( "Doctor" ); }
  if ( payee == "PeeryHotel") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "PeetsCoffee") { *f = 1; return( "Coffee" ); }
  if ( payee == "PekingUniversity") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "PelanchosMexicanGrill") { *f = 1; return( "Vacation" ); }
  if ( payee == "PentagonCity") { *f = 1; return( "Dining" ); }
  if ( payee == "PenzeysSpices") { *f = 1; return( "Groceries" ); }
  if ( payee == "PetersonSpirits") { *f = 1; return( "Groceries" ); }
  if ( payee == "Phils") { *f = 1; return( "Dining" ); }
  if ( payee == "Piccolo") { *f = 1; return( "Vacation" ); }
  if ( payee == "PilgrimMonument") { *f = 1; return( "Vacation" ); }
  if ( payee == "Pinkberry") { *f = 1; return( "Dining" ); }
  if ( payee == "Pinnacle") { *f = 1; return( "Dining" ); }
  if ( payee == "PitaHouse") { *f = 1; return( "Dining" ); }
  if ( payee == "PittsburghBagalFactory") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "PizzaHut") { *f = 1; return( "Dining" ); }
  if ( payee == "PizzeriaUno") { *f = 1; return( "Dining" ); }
  if ( payee == "PlanesMovingAndStorage") { *f = 1; return( "MovingStorage" ); }
  if ( payee == "Polo") { *f = 1; return( "Clothing" ); }
  if ( payee == "Popeyes") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "PortJeffFerry") { *f = 1; return( "Vacation" ); }
  if ( payee == "PortJeffersonBeverage") { *f = 1; return( "Groceries" ); }
  if ( payee == "PortJeffersonFrigate") { *f = 1; return( "Dining" ); }
  if ( payee == "PortageShell") { *f = 1; return( "Dining" ); }
  if ( payee == "PortoBello") { *f = 1; return( "Dining" ); }
  if ( payee == "PostalSavings") { *f = 1; return( "General" ); }
  if ( payee == "Potbelly") { *f = 1; return( "Dining" ); }
  if ( payee == "PotteryBarn") { *f = 1; return( "Furniture" ); }
  if ( payee == "PotteryBarnTeen") { *f = 1; return( "Furniture" ); }
  if ( payee == "PotteryBayou") { *f = 1; return( "Entertainment" ); }
  if ( payee == "PremiereClasse") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "Priceline") { *f = 1; return( "Travel" ); }
  if ( payee == "PrimierTitle") { *f = 1; return( "HomeDownPayment" ); }
  if ( payee == "PrincessByMomBoutique") { *f = 1; return( "Clothing" ); }
  if ( payee == "PriyaIndian") { *f = 1; return( "Dining" ); }
  if ( payee == "PrizmBehavioral") { *f = 1; return( "Doctor" ); }
  if ( payee == "ProHealth") { *f = 1; return( "Doctor" ); }
  if ( payee == "PublicStorage") { *f = 1; return( "Rent" ); }
  if ( payee == "Puma") { *f = 1; return( "Clothing" ); }
  if ( payee == "PumaOutletStore") { *f = 1; return( "Clothing" ); }
  if ( payee == "PumpItUp") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "Qdoba") { *f = 1; return( "Dining" ); }
  if ( payee == "QuestDiagnostic") { *f = 1; return( "Doctor" ); }
  if ( payee == "QuickCenter") { *f = 1; return( "Fuel" ); }
  if ( payee == "Quiznos") { *f = 1; return( "Dining" ); }
  if ( payee == "R2F5579EXKI_2F_1") { *f = 1; return( "Dining" ); }
  if ( payee == "REI") { *f = 1; return( "Clothing" ); }
  if ( payee == "REMOTE_ONLINE_DEPOSIT") { *f = 1; return( "Groceries" ); }
  if ( payee == "REVERSE_DEBIT_CARD_PROVISIONAL_CREDIT") { *f = 1; return( "CreditCard" ); }
  if ( payee == "RadioPerfecto") { *f = 1; return( "Dining" ); }
  if ( payee == "RadioShack") { *f = 1; return( "Entertainment" ); }
  if ( payee == "RadissonHotel") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "RailEurope") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "Ralphs") { *f = 1; return( "Groceries" ); }
  if ( payee == "RealMacSoftware") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "RedBox") { *f = 1; return( "Entertainment" ); }
  if ( payee == "RedBubble.com") { *f = 1; return( "General" ); }
  if ( payee == "RedCross") { *f = 1; return( "Charity" ); }
  if ( payee == "RedDoorTavern") { *f = 1; return( "Dining" ); }
  if ( payee == "RedHarkBar&Grill") { *f = 1; return( "Drinks" ); }
  if ( payee == "RedMango") { *f = 1; return( "Dining" ); }
  if ( payee == "RedRobin") { *f = 1; return( "Dining" ); }
  if ( payee == "RedRoofInn") { *f = 1; return( "Travel" ); }
  if ( payee == "Regal") { *f = 1; return( "Entertainment" ); }
  if ( payee == "RegalCinema") { *f = 1; return( "Entertainment" ); }
  if ( payee == "RegalCinemas") { *f = 1; return( "Vacation" ); }
  if ( payee == "Relay4152Midway") { *f = 1; return( "Dining" ); }
  if ( payee == "RenaissanceHotels") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "ResidenceInn") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "ReyesTung") { *f = 1; return( "Dining" ); }
  if ( payee == "RezaOnOntario") { *f = 1; return( "Dining" ); }
  if ( payee == "RibCityAleHouse") { *f = 1; return( "Dining" ); }
  if ( payee == "RidgeOil") { *f = 1; return( "Fuel" ); }
  if ( payee == "RistoranteKingsCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "RiteAid") { *f = 1; return( "General" ); }
  if ( payee == "RiverplaceReality") { *f = 1; return( "Rent" ); }
  if ( payee == "RiverplaceRealty") { *f = 1; return( "Rent" ); }
  if ( payee == "Riverside") { *f = 1; return( "Doctor" ); }
  if ( payee == "RiversidePsychiatric") { *f = 1; return( "Doctor" ); }
  if ( payee == "RiverwalkPizza") { *f = 1; return( "Dining" ); }
  if ( payee == "RobertMowinney") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "RochambeauWinesAndLiquors") { *f = 1; return( "Groceries" ); }
  if ( payee == "RockBottom") { *f = 1; return( "Dining" ); }
  if ( payee == "RomaDs") { *f = 1; return( "Dining" ); }
  if ( payee == "Romios") { *f = 1; return( "Dining" ); }
  if ( payee == "RotiRolls") { *f = 1; return( "Dining" ); }
  if ( payee == "Ruby") { *f = 1; return( "Dining" ); }
  if ( payee == "RubyTuesdays") { *f = 1; return( "Dining" ); }
  if ( payee == "RutgersAthletics") { *f = 1; return( "Entertainment" ); }
  if ( payee == "RuthHitSomeonesTailight") { *f = 1; return( "Service" ); }
  if ( payee == "SLACCafe") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "SLACGeustHouse") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "SLACGuestHouse") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "SPAQMontreal") { *f = 1; return( "Travel" ); }
  if ( payee == "Safeway") { *f = 1; return( "Groceries" ); }
  if ( payee == "SalsaSalsa") { *f = 1; return( "Dining" ); }
  if ( payee == "SamGol") { *f = 1; return( "Fuel" ); }
  if ( payee == "Samsonite") { *f = 1; return( "Furniture" ); }
  if ( payee == "SanDiegoZoo") { *f = 1; return( "Vacation" ); }
  if ( payee == "SangamRestaurant") { *f = 1; return( "Dining" ); }
  if ( payee == "SaraHiggins") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "Sbarro") { *f = 1; return( "Dining" ); }
  if ( payee == "ScarecrowVideo") { *f = 1; return( "Entertainment" ); }
  if ( payee == "SchenkQuickStop") { *f = 1; return( "Dining" ); }
  if ( payee == "ScholasticBookClub") { *f = 1; return( "General" ); }
  if ( payee == "SchwartzOBGYN") { *f = 1; return( "Doctor" ); }
  if ( payee == "ScottLantz") { *f = 1; return( "General" ); }
  if ( payee == "Sears") { *f = 1; return( "Service" ); }
  if ( payee == "SeasideCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "SeattlesBestCoffee") { *f = 1; return( "Coffee" ); }
  if ( payee == "Seaworld") { *f = 1; return( "Vacation" ); }
  if ( payee == "SecondCup") { *f = 1; return( "Dining" ); }
  if ( payee == "Seiko") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "SellMyTimeShareNow") { *f = 1; return( "Vacation" ); }
  if ( payee == "SequenomMolecular") { *f = 1; return( "Hospital" ); }
  if ( payee == "ServiceDirectionsInc") { *f = 1; return( "General" ); }
  if ( payee == "SetauketVillageDiner") { *f = 1; return( "Dining" ); }
  if ( payee == "SezzMedi") { *f = 1; return( "Dining" ); }
  if ( payee == "ShadeClothing") { *f = 1; return( "Clothing" ); }
  if ( payee == "ShawnMBolgerLtd") { *f = 1; return( "HomeDownPayment" ); }
  if ( payee == "SheddAquarium") { *f = 1; return( "Entertainment" ); }
  if ( payee == "Shell") { *f = 1; return( "Fuel" ); }
  if ( payee == "ShellOil") { *f = 1; return( "Fuel" ); }
  if ( payee == "ShellWarehouse") { *f = 1; return( "Fuel" ); }
  if ( payee == "Shopzoo.com") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "Shultzys") { *f = 1; return( "Dining" ); }
  if ( payee == "ShuttleExpress") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "SierraTradingPost") { *f = 1; return( "Clothing" ); }
  if ( payee == "SilverStateFoodMart") { *f = 1; return( "Fuel" ); }
  if ( payee == "SimplyGourmet") { *f = 1; return( "Dining" ); }
  if ( payee == "SivanaSalon") { *f = 1; return( "Hair" ); }
  if ( payee == "Skechers") { *f = 1; return( "Clothing" ); }
  if ( payee == "SloppyJoesBar") { *f = 1; return( "Dining" ); }
  if ( payee == "SmithtownToyota") { *f = 1; return( "CarPayment" ); }
  if ( payee == "SoYouThinkYouCanDance") { *f = 1; return( "Entertainment" ); }
  if ( payee == "SocieteDeVeloEnLib") { *f = 1; return( "Dining" ); }
  if ( payee == "SoftAsAGrape") { *f = 1; return( "Vacation" ); }
  if ( payee == "SoldierField") { *f = 1; return( "Entertainment" ); }
  if ( payee == "Solstice") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "SoundCatering") { *f = 1; return( "Vacation" ); }
  if ( payee == "Southwest") { *f = 1; return( "Travel" ); }
  if ( payee == "Spartys") { *f = 1; return( "Dining" ); }
  if ( payee == "SpatsBar") { *f = 1; return( "Dining" ); }
  if ( payee == "Speedway") { *f = 1; return( "Fuel" ); }
  if ( payee == "Split") { *f = 1; return( "Split" ); }
  if ( payee == "Sportograph") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "SportsScene") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "StElmosCoffee") { *f = 1; return( "Coffee" ); }
  if ( payee == "StJudes") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "StarMarket") { *f = 1; return( "Groceries" ); }
  if ( payee == "Starbucks") { *f = 1; return( "Coffee" ); }
  if ( payee == "StateFarm") { *f = 1; return( "RentersInsurance" ); }
  if ( payee == "StateOfIllinois") { *f = 1; return( "Taxes" ); }
  if ( payee == "SterlingPear") { *f = 1; return( "General" ); }
  if ( payee == "SteveMadden") { *f = 1; return( "Clothing" ); }
  if ( payee == "StirCrazy") { *f = 1; return( "Dining" ); }
  if ( payee == "StonyBrook") { *f = 1; return( "Dining" ); }
  if ( payee == "StonyBrookCosmeticDentistry") { *f = 1; return( "Doctor" ); }
  if ( payee == "StonyBrookFamilyMedice") { *f = 1; return( "Doctor" ); }
  if ( payee == "StonyBrookStudentAffairsCenter") { *f = 1; return( "Dining" ); }
  if ( payee == "StonyBrookTickets") { *f = 1; return( "Entertainment" ); }
  if ( payee == "StonyBrookUniversity") { *f = 1; return( "Doctor" ); }
  if ( payee == "StonyBrookUniversityHospital") { *f = 1; return( "Doctor" ); }
  if ( payee == "StonybrookChildrensHospital") { *f = 1; return( "Doctor" ); }
  if ( payee == "StopAndShop") { *f = 1; return( "Groceries" ); }
  if ( payee == "StopLiquors") { *f = 1; return( "Alcohol" ); }
  if ( payee == "StrideRite") { *f = 1; return( "Clothing" ); }
  if ( payee == "SuCasa") { *f = 1; return( "Clothing" ); }
  if ( payee == "Sublet.com") { *f = 1; return( "Rent" ); }
  if ( payee == "SubsConscious") { *f = 1; return( "Dining" ); }
  if ( payee == "Subsconcious") { *f = 1; return( "Dining" ); }
  if ( payee == "SuburbanMaternalFetalMedicine") { *f = 1; return( "Dining" ); }
  if ( payee == "Subway") { *f = 1; return( "Dining" ); }
  if ( payee == "SuffolkOBGYN") { *f = 1; return( "Doctor" ); }
  if ( payee == "SugarCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "SunCorners") { *f = 1; return( "Travel" ); }
  if ( payee == "SunkenMeadowStatePark") { *f = 1; return( "Entertainment" ); }
  if ( payee == "Sunoco") { *f = 1; return( "Travel" ); }
  if ( payee == "SunocoOil") { *f = 1; return( "Fuel" ); }
  if ( payee == "SunriseQ17Gas") { *f = 1; return( "Fuel" ); }
  if ( payee == "SuperLube") { *f = 1; return( "Service" ); }
  if ( payee == "SuperShuttle") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "SuperShuttleMN") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "SurLaTable") { *f = 1; return( "Furniture" ); }
  if ( payee == "Sura") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "SweetMariasCoffee") { *f = 1; return( "Coffee" ); }
  if ( payee == "SymantecSony") { *f = 1; return( "BankCharge" ); }
  if ( payee == "SyracuseUniversity") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "SysParkingLemoy") { *f = 1; return( "Entertainment" ); }
  if ( payee == "T1MedalistBarJFK") { *f = 1; return( "Dining" ); }
  if ( payee == "TAX_PRODUCTS_PE4_SBTPG_LLC") { *f = 1; return( "Taxes" ); }
  if ( payee == "TGIFridays") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "TIAACashContribution") { *f = 1; return( "BankCharge" ); }
  if ( payee == "TIAACashDividends") { *f = 1; return( "BankCharge" ); }
  if ( payee == "TIAACashLongTermCapitalGains") { *f = 1; return( "BankCharge" ); }
  if ( payee == "TIAACashShortTermCapitalGains") { *f = 1; return( "BankCharge" ); }
  if ( payee == "TIBMercerSt") { *f = 1; return( "Dining" ); }
  if ( payee == "TJMaxx") { *f = 1; return( "Clothing" ); }
  if ( payee == "TRANSACTION_FEE") { *f = 1; return( "BankCharge" ); }
  if ( payee == "TacoBell") { *f = 1; return( "Dining" ); }
  if ( payee == "TacoBron") { *f = 1; return( "Dining" ); }
  if ( payee == "TaisRestaurant") { *f = 1; return( "Dining" ); }
  if ( payee == "Talbots") { *f = 1; return( "Clothing" ); }
  if ( payee == "Tamomaro") { *f = 1; return( "Clothing" ); }
  if ( payee == "TampaMindWorks") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "TangoAngentinean") { *f = 1; return( "Dining" ); }
  if ( payee == "Target") { *f = 1; return( "Groceries" ); }
  if ( payee == "TastyWok") { *f = 1; return( "Vacation" ); }
  if ( payee == "TaxProducts") { *f = 1; return( "Taxes" ); }
  if ( payee == "TaxiMagic") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "TeaCollection") { *f = 1; return( "Vacation" ); }
  if ( payee == "TeaRoom") { *f = 1; return( "Dining" ); }
  if ( payee == "TeachersCreditUnion") { *f = 1; return( "Cash" ); }
  if ( payee == "TedsMontanaGrill") { *f = 1; return( "Dining" ); }
  if ( payee == "ThaiVillage") { *f = 1; return( "Dining" ); }
  if ( payee == "TheBlackDog") { *f = 1; return( "Vacation" ); }
  if ( payee == "TheBreadFactoryCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "TheCantina") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "TheCasualGourmet") { *f = 1; return( "Dining" ); }
  if ( payee == "TheCheeseShop") { *f = 1; return( "Dining" ); }
  if ( payee == "TheChristmasTreeStore") { *f = 1; return( "Vacation" ); }
  if ( payee == "TheCornellStore") { *f = 1; return( "Vacation" ); }
  if ( payee == "TheFamishedFrog") { *f = 1; return( "Dining" ); }
  if ( payee == "TheGroveChicago") { *f = 1; return( "Dining" ); }
  if ( payee == "TheHalfPint") { *f = 1; return( "Dining" ); }
  if ( payee == "TheHookerTeaCompany") { *f = 1; return( "Dining" ); }
  if ( payee == "TheLandOfNod") { *f = 1; return( "Clothing" ); }
  if ( payee == "TheMeltingPot") { *f = 1; return( "Dining" ); }
  if ( payee == "TheMeltonPot") { *f = 1; return( "Dining" ); }
  if ( payee == "TheMilburnHotel") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "TheNatureConservatory") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "TheOldGrapeCellar") { *f = 1; return( "Dining" ); }
  if ( payee == "TheOliveGarden") { *f = 1; return( "Dining" ); }
  if ( payee == "TheOliveGardon") { *f = 1; return( "Dining" ); }
  if ( payee == "ThePie") { *f = 1; return( "Dining" ); }
  if ( payee == "ThePortShop") { *f = 1; return( "Groceries" ); }
  if ( payee == "TheRepublicOfTea") { *f = 1; return( "Dining" ); }
  if ( payee == "TheSecondLandingCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "TheSoupKitchen") { *f = 1; return( "Vacation" ); }
  if ( payee == "TheSportsAuthority") { *f = 1; return( "Recreation" ); }
  if ( payee == "TheVillageAtSquawValley") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "TheVillageWay") { *f = 1; return( "Groceries" ); }
  if ( payee == "TheraProInc") { *f = 1; return( "Clothing" ); }
  if ( payee == "TicketMaster") { *f = 1; return( "Entertainment" ); }
  if ( payee == "Ticketmaster") { *f = 1; return( "Entertainment" ); }
  if ( payee == "Tiffany&Co") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "TimHortons") { *f = 1; return( "Dining" ); }
  if ( payee == "Timberland") { *f = 1; return( "Clothing" ); }
  if ( payee == "TitleNine") { *f = 1; return( "Clothing" ); }
  if ( payee == "Toast") { *f = 1; return( "Dining" ); }
  if ( payee == "TomPettyConcert") { *f = 1; return( "Entertainment" ); }
  if ( payee == "TomThumbOverseasMarathon") { *f = 1; return( "Dining" ); }
  if ( payee == "TomoSushi") { *f = 1; return( "Dining" ); }
  if ( payee == "TonyRomas") { *f = 1; return( "Dining" ); }
  if ( payee == "Tortilla") { *f = 1; return( "Dining" ); }
  if ( payee == "TownOfSchroon") { *f = 1; return( "Fines" ); }
  if ( payee == "ToyotaCamryFromSteve") { *f = 1; return( "CarPayment" ); }
  if ( payee == "ToyotaCarPayment") { *f = 1; return( "CarPayment" ); }
  if ( payee == "ToyotaOfNaperville") { *f = 1; return( "Service" ); }
  if ( payee == "ToysInBabeland") { *f = 1; return( "Entertainment" ); }
  if ( payee == "ToysRUs") { *f = 1; return( "General" ); }
  if ( payee == "TraderJoes") { *f = 1; return( "Groceries" ); }
  if ( payee == "TravelMart") { *f = 1; return( "Dining" ); }
  if ( payee == "Travelocity") { *f = 1; return( "Travel" ); }
  if ( payee == "TrendMicro") { *f = 1; return( "BankCharge" ); }
  if ( payee == "TufanLtd") { *f = 1; return( "Clothing" ); }
  if ( payee == "TugboatRestaurant") { *f = 1; return( "Vacation" ); }
  if ( payee == "TurboTax") { *f = 1; return( "Taxes" ); }
  if ( payee == "TuscanyCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "TwiceSoldTales") { *f = 1; return( "Entertainment" ); }
  if ( payee == "TwoBrothersTapHouse") { *f = 1; return( "Dining" ); }
  if ( payee == "TyroneHouse") { *f = 1; return( "Dining" ); }
  if ( payee == "UBCBookstore") { *f = 1; return( "Vacation" ); }
  if ( payee == "UBS") { *f = 1; return( "ATM" ); }
  if ( payee == "UCSantaBarbara") { *f = 1; return( "Dining" ); }
  if ( payee == "UDistrictBookStore") { *f = 1; return( "Entertainment" ); }
  if ( payee == "UHaul") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "UNICEF") { *f = 1; return( "GiftsGiven" ); }
  if ( payee == "USAGasStation") { *f = 1; return( "Fuel" ); }
  if ( payee == "USAToday") { *f = 1; return( "Dining" ); }
  if ( payee == "USAirway") { *f = 1; return( "Vacation" ); }
  if ( payee == "USDepartmentOfEducation") { *f = 1; return( "StudentLoan" ); }
  if ( payee == "USOpen") { *f = 1; return( "Entertainment" ); }
  if ( payee == "USPS") { *f = 1; return( "General" ); }
  if ( payee == "USTA") { *f = 1; return( "Entertainment" ); }
  if ( payee == "USTreasury") { *f = 1; return( "Taxes" ); }
  if ( payee == "UWInpatientPharmacy") { *f = 1; return( "Doctor" ); }
  if ( payee == "UWMCExpresso") { *f = 1; return( "Dining" ); }
  if ( payee == "UggStore") { *f = 1; return( "Clothing" ); }
  if ( payee == "Uhaul") { *f = 1; return( "Travel" ); }
  if ( payee == "UnclePetesPizza") { *f = 1; return( "Dining" ); }
  if ( payee == "UnionFoodCourt") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "UnionOutTakes") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "United") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "UnitedAirlines") { *f = 1; return( "Travel" ); }
  if ( payee == "UniversityFoodGrill") { *f = 1; return( "Vacation" ); }
  if ( payee == "UniversityGrill&Pizza") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "UniversityHardware") { *f = 1; return( "Furniture" ); }
  if ( payee == "UniversityHouseware") { *f = 1; return( "Furniture" ); }
  if ( payee == "UniversityOfChicagoMedical") { *f = 1; return( "Doctor" ); }
  if ( payee == "UniversityOfCinncinnati") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "UniversityOfMaryland") { *f = 1; return( "Dining" ); }
  if ( payee == "UniversityOfMichigan") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "UniversityOfMinnesota") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "UniversityOfMinnesotaBookstore") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "UniversityOfOxford") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "UniversityOfUtahWebPayment") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "UniversityOfWashington") { *f = 1; return( "ThomasSalary" ); }
  if ( payee == "UniversityOfWashingtonSalary") { *f = 1; return( "ThomasSalary" ); }
  if ( payee == "UniversityOfWashingtonTuition") { *f = 1; return( "School" ); }
  if ( payee == "UniversityTeriyaki") { *f = 1; return( "Dining" ); }
  if ( payee == "UniversityofPittsburgh") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "Upkeepers") { *f = 1; return( "Furniture" ); }
  if ( payee == "UpperCrustJFK") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "UrbanTaco") { *f = 1; return( "Dining" ); }
  if ( payee == "UsOpen") { *f = 1; return( "Entertainment" ); }
  if ( payee == "VX510") { *f = 1; return( "Fuel" ); }
  if ( payee == "ValdostanaLaThuille") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "Valero") { *f = 1; return( "Fuel" ); }
  if ( payee == "VendingAtCocaCola") { *f = 1; return( "Dining" ); }
  if ( payee == "VeraBradley") { *f = 1; return( "Clothing" ); }
  if ( payee == "VeraBrandley") { *f = 1; return( "Clothing" ); }
  if ( payee == "Verizon") { *f = 1; return( "Phone" ); }
  if ( payee == "VictoriaSecret") { *f = 1; return( "Clothing" ); }
  if ( payee == "VictoriasSecret") { *f = 1; return( "Clothing" ); }
  if ( payee == "VillaPizza") { *f = 1; return( "Dining" ); }
  if ( payee == "VillagePontiac") { *f = 1; return( "Service" ); }
  if ( payee == "WAPBoston") { *f = 1; return( "Dining" ); }
  if ( payee == "WBEZ") { *f = 1; return( "Charity" ); }
  if ( payee == "WHSmith") { *f = 1; return( "Dining" ); }
  if ( payee == "WIRE_TRANSFER_DEPOSIT") { *f = 1; return( "GiftReceived" ); }
  if ( payee == "WNYC") { *f = 1; return( "Charity" ); }
  if ( payee == "WOOTInc") { *f = 1; return( "Clothing" ); }
  if ( payee == "WSHU") { *f = 1; return( "Charity" ); }
  if ( payee == "WSOutlet") { *f = 1; return( "Entertainment" ); }
  if ( payee == "WalMart") { *f = 1; return( "General" ); }
  if ( payee == "Waldbaums") { *f = 1; return( "Groceries" ); }
  if ( payee == "Walgreens") { *f = 1; return( "Medicine" ); }
  if ( payee == "WashingtonMetroRail") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "WashingtonMutual") { *f = 1; return( "CreditCard" ); }
  if ( payee == "WaterwheelLiquors") { *f = 1; return( "Vacation" ); }
  if ( payee == "WaverlyLiquors") { *f = 1; return( "Groceries" ); }
  if ( payee == "WeBringThe") { *f = 1; return( "Clothing" ); }
  if ( payee == "Wendys") { *f = 1; return( "Dining" ); }
  if ( payee == "WestElm") { *f = 1; return( "Furniture" ); }
  if ( payee == "WestSuburbanLimo") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "Westin") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "WestoneLaboraties") { *f = 1; return( "Doctor" ); }
  if ( payee == "WestsideMarket") { *f = 1; return( "Groceries" ); }
  if ( payee == "WexnerCafe") { *f = 1; return( "Dining" ); }
  if ( payee == "WhistleStop") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "WhiteHen") { *f = 1; return( "Groceries" ); }
  if ( payee == "WhiteHouseSubs") { *f = 1; return( "Dining" ); }
  if ( payee == "WholeFoods") { *f = 1; return( "Groceries" ); }
  if ( payee == "WilcoOil") { *f = 1; return( "Fuel" ); }
  if ( payee == "WildBirdCenter") { *f = 1; return( "Entertainment" ); }
  if ( payee == "WildBirdsUnlimited") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "WildByNature") { *f = 1; return( "Groceries" ); }
  if ( payee == "WildOutWest") { *f = 1; return( "TVInternet" ); }
  if ( payee == "WilliamAndMary") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "WilliamsSonoma") { *f = 1; return( "Furniture" ); }
  if ( payee == "WilliamsSonona") { *f = 1; return( "Furniture" ); }
  if ( payee == "WilliamsburgHospitalityHouse") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "Wings") { *f = 1; return( "Vacation" ); }
  if ( payee == "WinterthurMuseum") { *f = 1; return( "Entertainment" ); }
  if ( payee == "WiscassetClipper") { *f = 1; return( "Vacation" ); }
  if ( payee == "WokAndRoll") { *f = 1; return( "Dining" ); }
  if ( payee == "WorldFamousKaysPizza") { *f = 1; return( "Dining" ); }
  if ( payee == "WorldPantry.com") { *f = 1; return( "Dining" ); }
  if ( payee == "WorldWildlifeFund") { *f = 1; return( "Charity" ); }
  if ( payee == "WyndhamPittsburg") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "YankeeStadium") { *f = 1; return( "Entertainment" ); }
  if ( payee == "YogurtCrazy") { *f = 1; return( "Dining" ); }
  if ( payee == "YouMeAndTea") { *f = 1; return( "Dining" ); }
  if ( payee == "Yoyo.com") { *f = 1; return( "Clothing" ); }
  if ( payee == "ZMarketMaryland") { *f = 1; return( "Dining" ); }
  if ( payee == "ZPita") { *f = 1; return( "Dining" ); }
  if ( payee == "ZanesTavern") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "ZapposDevelopment.6pm.com") { *f = 1; return( "Clothing" ); }
  if ( payee == "ZazuSalon") { *f = 1; return( "Hair" ); }
  if ( payee == "Zazzle.com") { *f = 1; return( "Clothing" ); }
  if ( payee == "ZeytinRestaurant") { *f = 1; return( "Dining" ); }
  if ( payee == "ZocaloGrill") { *f = 1; return( "Dining" ); }
  if ( payee == "Zoup") { *f = 1; return( "Dining" ); }
  if ( payee == "Zulily") { *f = 1; return( "Clothing" ); }
  if ( payee == "www.abebooks.com") { *f = 1; return( "Entertainment" ); }
  if ( payee == "www.alexandalexa.com") { *f = 1; return( "Clothing" ); }
  if ( payee == "www.asos.com") { *f = 1; return( "Clothing" ); }
  if ( payee == "www.bookworm.com") { *f = 1; return( "Entertainment" ); }
  if ( payee == "www.ebags.com") { *f = 1; return( "Clothing" ); }
  if ( payee == "www.myhabit.com") { *f = 1; return( "Entertainment" ); }
  if ( payee == "www.store.motorola.com") { *f = 1; return( "WorkTravel" ); }
  if ( payee == "www.teamfanshop.com") { *f = 1; return( "Clothing" ); }
  if ( payee == "www.wiworldstore.com") { *f = 1; return( "GiftsGiven" ); }
  *f = 0;
  return( "NOCATEGORY" );
}