string IDCategory(int id)
{
  if ( id == 0 ) { return( "NoCategory" ); }
  if ( id == 1 ) { return( "Alcohol" ); }
  if ( id == 2 ) { return( "BankCharge" ); }
  if ( id == 3 ) { return( "CarInsurance" ); }
  if ( id == 4 ) { return( "CarPayment" ); }
  if ( id == 5 ) { return( "Charity" ); }
  if ( id == 6 ) { return( "Check" ); }
  if ( id == 7 ) { return( "ChildCare" ); }
  if ( id == 8 ) { return( "Clothing" ); }
  if ( id == 9 ) { return( "Coffee" ); }
  if ( id == 10 ) { return( "CollegeFund" ); }
  if ( id == 11 ) { return( "CreditCard" ); }
  if ( id == 12 ) { return( "Dining" ); }
  if ( id == 13 ) { return( "Doctor" ); }
  if ( id == 14 ) { return( "Drinks" ); }
  if ( id == 15 ) { return( "Education" ); }
  if ( id == 16 ) { return( "Entertainment" ); }
  if ( id == 17 ) { return( "Fines" ); }
  if ( id == 18 ) { return( "Fuel" ); }
  if ( id == 19 ) { return( "Furniture" ); }
  if ( id == 20 ) { return( "GasElectric" ); }
  if ( id == 21 ) { return( "General" ); }
  if ( id == 22 ) { return( "GiftReceived" ); }
  if ( id == 23 ) { return( "GiftsGiven" ); }
  if ( id == 24 ) { return( "Groceries" ); }
  if ( id == 25 ) { return( "Hair" ); }
  if ( id == 26 ) { return( "HomeDownPayment" ); }
  if ( id == 27 ) { return( "Hospital" ); }
  if ( id == 28 ) { return( "HouseDownPayment" ); }
  if ( id == 29 ) { return( "Laundry" ); }
  if ( id == 30 ) { return( "License" ); }
  if ( id == 31 ) { return( "LocalTravel" ); }
  if ( id == 32 ) { return( "Medicine" ); }
  if ( id == 33 ) { return( "Mortgage" ); }
  if ( id == 34 ) { return( "MovingStorage" ); }
  if ( id == 35 ) { return( "OpeningBalance" ); }
  if ( id == 36 ) { return( "Phone" ); }
  if ( id == 37 ) { return( "Recreation" ); }
  if ( id == 38 ) { return( "Registration" ); }
  if ( id == 39 ) { return( "Rent" ); }
  if ( id == 40 ) { return( "RentersInsurance" ); }
  if ( id == 41 ) { return( "RuthIRA" ); }
  if ( id == 42 ) { return( "RuthSalary" ); }
  if ( id == 43 ) { return( "School" ); }
  if ( id == 44 ) { return( "SecurityDeposit" ); }
  if ( id == 45 ) { return( "Service" ); }
  if ( id == 46 ) { return( "Split" ); }
  if ( id == 47 ) { return( "StudentLoan" ); }
  if ( id == 48 ) { return( "TVInternet" ); }
  if ( id == 49 ) { return( "TaxRefund" ); }
  if ( id == 50 ) { return( "Taxes" ); }
  if ( id == 51 ) { return( "ThomasIRA" ); }
  if ( id == 52 ) { return( "ThomasSalary" ); }
  if ( id == 53 ) { return( "Tolls" ); }
  if ( id == 54 ) { return( "Travel" ); }
  if ( id == 55 ) { return( "Vacation" ); }
  if ( id == 56 ) { return( "WorkTravel" ); }
  return( "NoCategory" );
}
